server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anoop18/ConfigServer
          clone-on-start: true
          
  